name: Bump version and update changelog
on:
  # Manually triggered
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch name'
        required: true
        default: 'master'

jobs:
  bump-version-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.target_branch }}
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.FUEL_BOT_PAT }}
          tag-prefix: ''
          release-count: '0'
          config-file-path: '.github/conventional-changelog.js'
          git-branch: ${{ inputs.target_branch }}
