name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Check code formatter
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check client/src snippets syntaxes

  publish-marketplace-test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Dry run publish
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          dryRun: true

