name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci

  check-format:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Check code format
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check client/src snippets syntaxes

  publish-marketplace-test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Dry run publish
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: "quickbrownfox"
          dryRun: true
